### ISSUE TITLE
Composer 10 Beta 5 - Notes in the frontend - it lacks Images

### ISSUE THREAD

**Issue by AlexL777** [ocproducts/composr#13]
Hello Developers,

I am a ocPortal fan for a while now and have noticed that you have developed the Composr CMS. I installed it and get in the frontend these notes.

    No such theme image, icons/24x24/menu/rich_content/downloads.
    No such theme image, icons/24x24/menu/rich_content/galleries.
    No such theme image, icons/24x24/menu/site_meta/bookmarks.
    No such theme image, icons/24x24/menu/site_meta/recommend.

Apparently missing images in the template and I do not know how I can fix the problem.

Can you possibly help me?

Thanks in advance.

**Comment by chrisgraham** [comment]
Hi Alex,

It looks like a few addons were uninstalled, but somehow icons for them are still being used. This should not normally be possible because all references to them go with the addons.

However, I wonder if it's the case that you had already edited the default menu to lock it in, before removing those addons. If that's the case you'd need to edit it and remove the broken menu links.

I'm going to close this issue because actually I did not realise we had issues enabled on the github repository. If there's still an issue please post in http://compo.sr/tracker
